from google import genai
import json
import re
from typing import Dict, List, Any, Tuple

class LessonEditorAgent:
    """Agent responsible for editing lessons based on natural language instructions"""
    
    def __init__(self, api_key: str):
        self.client = genai.Client(api_key=api_key)
        self.model_name = 'gemini-2.5-flash-lite'
        
    def process_edit_request(self, lesson_data: Dict[str, Any], user_request: str) -> Tuple[Dict[str, Any], List[str]]:
        """
        Process a natural language edit request and return updated lesson data
        Returns: (updated_lesson_data, list_of_image_sections_to_regenerate)
        """
        
        prompt = f"""You are an AI assistant that edits educational lesson content based on user requests.

Current lesson (JSON):
{json.dumps(lesson_data, indent=2)}

User's request: "{user_request}"

Generate the COMPLETE UPDATED lesson as JSON. Make the changes requested by the user while keeping all other content intact.

If the user wants to change an image style (e.g., "make introduction image cartoon"), update the image_prompt to reflect that style.

Return ONLY the complete updated lesson JSON, no markdown or extra text."""

        try:
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=[prompt]
            )
            
            # Extract text from response
            response_text = ""
            if hasattr(response, 'text') and response.text:
                response_text = response.text
            elif hasattr(response, 'candidates') and response.candidates:
                for candidate in response.candidates:
                    if hasattr(candidate, 'content') and candidate.content:
                        for part in candidate.content.parts:
                            if hasattr(part, 'text') and part.text:
                                response_text += part.text
            
            response_text = response_text.strip()
            
            # Clean up markdown formatting
            response_text = re.sub(r'^```json\s*', '', response_text)
            response_text = re.sub(r'\s*```$', '', response_text)
            
            updated_lesson = json.loads(response_text)
            
            # Detect which images need to be regenerated by comparing prompts
            image_sections = self._detect_image_changes(lesson_data, updated_lesson, user_request)
            
            # Increment version
            updated_lesson['version'] = lesson_data.get('version', 1) + 1
            
            return updated_lesson, image_sections
            
        except Exception as e:
            print(f"Error processing edit request: {e}")
            import traceback
            traceback.print_exc()
            return lesson_data, []
    
    def _detect_image_changes(self, old_lesson: Dict[str, Any], new_lesson: Dict[str, Any], user_request: str) -> List[Dict[str, Any]]:
        """Detect which images need to be regenerated"""
        image_sections = []
        
        # Check if user explicitly requested image changes
        image_keywords = ['image', 'picture', 'illustration', 'cartoon', 'realistic', 'diagram', 'photo']
        request_lower = user_request.lower()
        wants_image_change = any(keyword in request_lower for keyword in image_keywords)
        
        if not wants_image_change:
            return image_sections
        
        # Detect style from request
        style = 'educational'
        if 'cartoon' in request_lower:
            style = 'cartoon'
        elif 'realistic' in request_lower or 'photo' in request_lower:
            style = 'realistic'
        elif 'minimalist' in request_lower:
            style = 'minimalist'
        elif 'diagram' in request_lower:
            style = 'diagram'
        
        # Check introduction image
        if 'introduction' in request_lower or 'intro' in request_lower:
            if 'introduction' in new_lesson and 'image_prompt' in new_lesson['introduction']:
                image_sections.append({
                    'section': 'introduction',
                    'index': None,
                    'prompt': new_lesson['introduction']['image_prompt'],
                    'style': style
                })
        
        # Check activities image
        if 'activit' in request_lower:
            if 'activities' in new_lesson and 'image_prompt' in new_lesson['activities']:
                image_sections.append({
                    'section': 'activities',
                    'index': None,
                    'prompt': new_lesson['activities']['image_prompt'],
                    'style': style
                })
        
        # Check key concepts
        if 'concept' in request_lower or 'key' in request_lower:
            if 'key_concepts' in new_lesson:
                for idx, concept in enumerate(new_lesson['key_concepts']):
                    if 'image_prompt' in concept:
                        image_sections.append({
                            'section': 'key_concepts',
                            'index': idx,
                            'prompt': concept['image_prompt'],
                            'style': style
                        })
        
        # If user said "all images" or similar, regenerate all
        if 'all image' in request_lower or 'every image' in request_lower:
            image_sections = []
            
            if 'introduction' in new_lesson and 'image_prompt' in new_lesson['introduction']:
                image_sections.append({
                    'section': 'introduction',
                    'index': None,
                    'prompt': new_lesson['introduction']['image_prompt'],
                    'style': style
                })
            
            if 'key_concepts' in new_lesson:
                for idx, concept in enumerate(new_lesson['key_concepts']):
                    if 'image_prompt' in concept:
                        image_sections.append({
                            'section': 'key_concepts',
                            'index': idx,
                            'prompt': concept['image_prompt'],
                            'style': style
                        })
            
            if 'activities' in new_lesson and 'image_prompt' in new_lesson['activities']:
                image_sections.append({
                    'section': 'activities',
                    'index': None,
                    'prompt': new_lesson['activities']['image_prompt'],
                    'style': style
                })
        
        return image_sections
